-- NOTE: The selected fields has aliases in uppercase to make them similar to actual created fields in the database table

SELECT
    ofc.ORDER_FACILITY_CHANGE_ID AS `ORDER_FACILITY_CHANGE_ID`,
    ofc.ORDER_ID AS `ORDER_ID`,
    ofc.ORDER_ITEM_SEQ_ID AS `ORDER_ITEM_SEQ_ID`,
    oh.PRODUCT_STORE_ID AS `PRODUCT_STORE_ID`,
    ofc.SHIPMENT_METHOD_TYPE_ID AS `SHIPMENT_METHOD_TYPE_ID`,
    ofc.FROM_FACILITY_ID AS `FROM_FACILITY_ID`,
    ofc.FACILITY_ID AS `FACILITY_ID`,
    ofc.CHANGE_DATETIME AS `CHANGE_DATETIME`,
    ofc.CHANGE_REASON_ENUM_ID AS `CHANGE_REASON_ENUM_ID`,
    ofc.COMMENTS AS `COMMENTS`,
    ofc.CHANGE_USER_LOGIN AS `CHANGE_USER_LOGIN`,
    ofc.ORDER_ROUTING_ID AS `ORDER_ROUTING_ID`,
    oru.ROUTING_NAME AS `ORDER_ROUTING_NAME`,
    ofc.ROUTING_RUN_ID AS `ROUTING_RUN_ID`,
    ofc.ROUTING_RULE AS `ROUTING_RULE`,
    ofc.ROUTING_RULE_ID AS `ROUTING_RULE_ID`,
    orr.RULE_NAME AS `ROUTING_RULE_NAME`,
    ofc.ROUTING_GROUP_ID AS `ROUTING_GROUP_ID`,
    org.GROUP_NAME AS `ROUTING_GROUP_NAME`,
    orun.ROUTING_BATCH_ID AS `ROUTING_BATCH_ID`,
    ofc.ROUTER_USER_LOGIN AS `ROUTER_USER_LOGIN`,
    orr.ASSIGNMENT_ENUM_ID AS `ASSIGNMENT_ENUM_ID`,
    ofc.CHANGE_DATETIME AS `cursorDate`
FROM order_facility_change ofc
JOIN order_header oh ON oh.ORDER_ID = ofc.ORDER_ID
JOIN order_routing_group org ON org.ROUTING_GROUP_ID = ofc.ROUTING_GROUP_ID
JOIN order_routing oru ON oru.ORDER_ROUTING_ID = ofc.ORDER_ROUTING_ID
JOIN order_routing_rule orr ON orr.ROUTING_RULE_ID = ofc.ROUTING_RULE_ID
JOIN order_routing_run orun ON orun.ROUTING_RUN_ID = ofc.ROUTING_RUN_ID