SELECT
  ri.RETURN_ID AS `RETURN_ID`,
  ri.RETURN_ITEM_SEQ_ID AS `RETURN_ITEM_SEQ_ID`,
  ri.RETURN_PRICE AS `RETURN_PRICE`,
  ri.DESCRIPTION AS `RETURN_ITEM_DESCRIPTION`,
  ri.RETURN_ITEM_TYPE_ID AS `RETURN_ITEM_TYPE_ID`,
  rh.RETURN_HEADER_TYPE_ID AS `RETURN_TYPE_ID`,
  DATE_FORMAT(rh.RETURN_DATE, "%Y-%m-%d %H:%i:%s") AS `RETURN_DATE`,
  DATE_FORMAT(rh.ENTRY_DATE, "%Y-%m-%d %H:%i:%s") AS `RETURN_ENTRY_DATE`,
  rh.STATUS_ID AS `RETURN_STATUS_ID`,
  ri.STATUS_ID AS `RETURN_ITEM_STATUS_ID`,
  rh.DESTINATION_FACILITY_ID AS `DESTINATION_FACILITY_ID`,
  rh.EMPLOYEE_ID AS `EMPLOYEE_ID`,
  rh.CREATED_BY AS `CREATED_BY_USER_LOGIN`,
  rh.RETURN_CHANNEL_ENUM_ID AS `RETURN_CHANNEL_ENUM_ID`,
  ri.RETURN_REASON_ID AS `RETURN_REASON_ID`,
  ri.RECEIVED_QUANTITY AS `RECEIVED_QUANTITY`,
  ri.RETURN_QUANTITY AS `RETURN_QUANTITY`,
  ri.ORDER_ID AS `ORDER_ID`,
  ri.ORDER_ITEM_SEQ_ID AS `ORDER_ITEM_SEQ_ID`,
  ri.PRODUCT_ID AS `PRODUCT_ID`,
  (
    SELECT rtni.ID_VALUE
    FROM return_identification rtni
    WHERE rtni.RETURN_ID = rh.RETURN_ID
      AND rtni.RETURN_IDENTIFICATION_TYPE_ID = "SHOPIFY_RTN_ID"
      AND (thru_date > NOW() OR thru_date IS NULL)
  ) AS `EXTERNAL_RETURN_ID`,
  "SHOPIFY" AS `DATA_SOURCE_ID`,
  ris.SHIPMENT_ID AS `RETURN_SHIPMENT_ID`,
  (
    SELECT SUM(opp.MAX_AMOUNT)
    FROM return_item_response ris
    JOIN order_payment_preference opp ON opp.ORDER_PAYMENT_PREFERENCE_ID = ris.ORDER_PAYMENT_PREFERENCE_ID
    WHERE ris.RETURN_ID = rh.RETURN_ID
      AND ris.RETURN_ITEM_SEQ_ID = "_NA_"
      AND opp.STATUS_ID = "PAYMENT_REFUNDED"
  ) AS `RETURN_REFUNDED_TOTAL`,
  (
    SELECT SUM(ra.AMOUNT)
    FROM return_adjustment ra
    WHERE ra.RETURN_ID = ri.RETURN_ID
      AND ra.RETURN_ITEM_SEQ_ID = ri.RETURN_ITEM_SEQ_ID
      AND ra.RETURN_ADJUSTMENT_TYPE_ID = 'RET_EXT_PRM_ADJ'
      AND ra.RETURN_TYPE_ID = 'RTN_REFUND'
  ) AS `RETURN_DISCOUNT_AMT`,
  (
    SELECT SUM(ra.AMOUNT)
    FROM return_adjustment ra
    WHERE ra.RETURN_ID = ri.RETURN_ID
      AND ra.RETURN_ITEM_SEQ_ID = ri.RETURN_ITEM_SEQ_ID
      AND ra.RETURN_ADJUSTMENT_TYPE_ID = 'RET_SALES_TAX_ADJ'
      AND ra.RETURN_TYPE_ID = 'RTN_REFUND'
  ) AS `TOTAL_TAX_REFUND_AMT`,
  (
    SELECT SUM(ra.AMOUNT)
    FROM return_adjustment ra
    WHERE ra.RETURN_ID = ri.RETURN_ID
      AND ra.RETURN_ITEM_SEQ_ID = "_NA_"
      AND ra.RETURN_ADJUSTMENT_TYPE_ID = 'RET_SHIPPING_ADJ'
      AND ra.RETURN_TYPE_ID = 'RTN_REFUND'
  ) AS `RETURN_SHIPPING_AMT`,
  DATE_FORMAT(rs.STATUS_DATETIME, "%Y-%m-%d %H:%i:%s") AS `RETURN_ITEM_COMPLETED_DATE`,
  DATE_FORMAT(rs1.STATUS_DATETIME, "%Y-%m-%d %H:%i:%s") AS `RETURN_ITEM_RECEIVED_DATE`,
  rs1.CHANGE_BY_USER_LOGIN_ID AS `RECEIVED_BY_USER_LOGIN`,
  oh.ORDER_TYPE_ID AS `ORDER_TYPE_ID`,
  oh.ORDER_NAME AS `ORDER_NAME`,
  oh.EXTERNAL_ID AS `EXTERNAL_ID`,
  oh.SALES_CHANNEL_ENUM_ID AS `SALES_CHANNEL_ENUM_ID`,
  DATE_FORMAT(oh.ORDER_DATE, "%Y-%m-%d %H:%i:%s") AS `ORDER_DATE`,
  DATE_FORMAT(oh.ENTRY_DATE, "%Y-%m-%d %H:%i:%s") AS `ORDER_ENTRY_DATE`,
  oh.PRIORITY AS `PRIORITY`,
  oh.ORIGIN_FACILITY_ID AS `ORDER_ORIGIN_FACILITY_ID`,
  oh.PRODUCT_STORE_ID AS `PRODUCT_STORE_ID`,
  pa.CITY AS `ORDER_ORG_CITY`,
  pa.POSTAL_CODE AS `ORDER_ORG_POSTAL_CODE`,
  pa.COUNTRY_GEO_ID AS `ORDER_ORG_COUNTRY_GEO_ID`,
  pa.STATE_PROVINCE_GEO_ID AS `ORDER_ORG_STATE_PROVINCE_GEO_ID`,
  pa.MUNICIPALITY_GEO_ID AS `ORDER_ORG_MUNICIPALITY_GEO_ID`,
  pa.LONGITUDE AS `ORDER_ORG_LONGITUDE`,
  pa.LATITUDE AS `ORDER_ORG_LATITUDE`,
  rs.CREATED_TX_STAMP AS 'cursorDate'
FROM return_item ri
JOIN return_header rh ON rh.RETURN_ID = ri.RETURN_ID
JOIN return_status rs ON rs.RETURN_ID = ri.RETURN_ID
    AND rs.RETURN_ITEM_SEQ_ID = ri.RETURN_ITEM_SEQ_ID
    AND ri.STATUS_ID = rs.STATUS_ID
    AND ri.STATUS_ID = "RETURN_COMPLETED"
LEFT JOIN order_header oh ON oh.ORDER_ID = ri.ORDER_ID
LEFT JOIN (
  select ocm.order_id, ocm.CONTACT_MECH_ID
  FROM order_contact_mech ocm
  WHERE ocm.CONTACT_MECH_PURPOSE_TYPE_ID = "SHIPPING_LOCATION"
  group by ocm.order_id
) ocm1 on ocm1.order_id = ri.order_id
LEFT JOIN postal_address pa ON pa.CONTACT_MECH_ID = ocm1.CONTACT_MECH_ID
LEFT JOIN return_status rs1 ON rs1.RETURN_ID = ri.RETURN_ID
    AND rs1.RETURN_ITEM_SEQ_ID = ri.RETURN_ITEM_SEQ_ID
    AND rs1.STATUS_ID = "RETURN_RECEIVED"
LEFT JOIN return_item_shipment ris ON ris.RETURN_ID = ri.RETURN_ID
    AND ris.RETURN_ITEM_SEQ_ID = ri.RETURN_ITEM_SEQ_ID